# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sentry to NR

on:
  push:
    branches:
      - master
      - jira
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm start
      env:
        SENTRY_AUTH: ${{ secrets.SENTRY_AUTH }}
        NEW_RELIC_AUTH: ${{ secrets.NEW_RELIC_AUTH }}
        NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
        JIRA_AUTH: ${{ secrets.JIRA_AUTH }}
